# application.yaml uygulamanın konfigurasyon tanimlarini içerir.
# Runtime'da external propertieslere bind edilir.

# asagidaki keywordleri iceren tweetleri twitterdan okuyacağız.
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch

  welcome-message: Hello Microservices
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  sleep-ms: 1000

port: 8090